USE GodsChaosGame;



INSERT INTO Abilities (Sort, Name, Type, TriggerDamage, `Trigger`, ResultDamage, Result, MinRank, LevelUpRanks) 
VALUES 
	(1, 'Summon Hellions', 'Strength', 'NA', 'NA', 'Medium', 'Knock-Down', 0, '50, 100'), 
	(2, 'Strke', 'Strength', 'NA', 'NA', 'Medium', 'Knock-Down', 0, '10, 70'), 
	(3, 'Sould Drain', 'Strength', 'Medium', 'Mid-Air', 'Medium', 'Knock-Down', 20, '20, 40, 80'), 
	(1, 'Divine Touch', 'Wisdom', 'NA', 'NA', 'Small', 'Healing', 0, '50, 100'), 
	(2, 'Crescent Blade', 'Wisdom', 'NA', 'NA', 'Small', 'Knock-Back', 0, '10, 70'), 
	(3, 'Divine Retribution', 'Wisdom', 'High', 'Mid-Air', 'NA', 'Knock-Back', 20, '20, 40, 80'), 
	(1, 'Summon Murder', 'Strength', 'NA', 'NA', 'Small', 'Mid-Air', 0, '50, 100'), 
	(2, 'Thrust', 'Strength', 'NA', 'NA', 'Small', 'Mid-Air', 0, '10, 70'), 
	(3, 'Energy Shot', 'Strength', 'NA', 'Knock-Back', 'Large', 'Mid-Air', 20, '20, 40, 80'), 
	(1, 'Thunder Strike', 'Strength', 'NA', 'NA', 'Small', 'Knock-Down', 0, '50, 100'), 
	(2, 'Hammer Strike', 'Strength', 'NA', 'NA', 'Small', 'Knock-Down', 0, '10, 70'), 
	(3, 'Thunderous Blow', 'Strength', 'Large', 'Mid-Air', 'NA', 'Mid-Air', 20, '20, 40, 80'), 
	(1, 'Demonic Skin', 'Wisdom', 'NA', 'NA', 'Small', 'Knock-Back', 0, '50, 100'), 
	(2, 'Dark Fireball', 'Wisdom', 'NA', 'NA', 'Small', 'Mid-Air', 0, '10, 70'), 
	(3, 'Demonic Slap', 'Wisdom', 'Large', 'Knock-Down', 'NA', 'Mid-Air', 20, '20, 40, 80'), 
	(1, 'Sword Dance', 'Strength', 'NA', 'NA', 'Small', 'Knock-Back', 0, '50, 100'), 
	(2, 'Swing', 'Strength', 'NA', 'NA', 'Small', 'Knock-Down', 0, '10, 70'), 
	(3, 'Phandom Strike', 'Strength', 'Large', 'Mid-Air', 'NA', 'Knock-Back', 20, '20, 40, 80'), 
	(1, 'Ball Lightning', 'Wisdom', 'NA', 'NA', 'Small', 'Mid-Air', 0, '50, 100'), 
	(2, 'Chain Lightning', 'Wisdom', 'NA', 'NA', 'Small', 'Knock-Back', 0, '10, 70'), 
	(3, 'Lightning Ball', 'Wisdom', 'Large', 'Flying', 'NA', 'Knock-Down', 20, '20, 40, 80'), 
	(1, 'Arcane Storm', 'Wisdom', 'NA', 'NA', 'Small', 'Mid-Air', 0, '50, 100'), 
	(2, 'Arcane Orb', 'Wisdom', 'NA', 'NA', 'Small', 'Knock-Back', 0, '10, 70'), 
	(3, 'Arcane Blast', 'Wisdom', 'Large', 'Flying', 'NA', 'Knock-Back', 20, '20, 40, 80'), 
	(1, 'Demonic Influence', 'Strength', 'NA', 'NA', 'Small', 'Knock-Down', 0, '50, 100'), 
	(3, 'Arcane Purp', 'Strength', 'Large', 'Knock-Down', 'NA', 'Mid-Air', 20, '20, 40, 80'), 
	(1, 'Summon Sea Dragon', 'Strength', 'NA', 'NA', 'Small', 'Knock-Down', 0, '50, 100'), 
	(3, 'Summon Piranhas', 'Strength', 'Large', 'Knock-Down', 'NA', 'Knock-Back', 20, '20, 40, 80'), 
	(1, 'Cyber Cannon', 'Wisdom', 'NA', 'NA', 'Small', 'Mid-Air', 0, '50, 100'), 
	(2, 'Spider Blast', 'Wisdom', 'NA', 'NA', 'Small', 'Knock-Back', 0, '10, 70'), 
	(3, 'Bully Spider', 'Wisdom', 'Medium', 'Knock-Down', 'NA', 'Knock-Back', 20, '20, 40, 80'), 
	(1, 'Gale Force', 'Strength', 'NA', 'NA', 'Small', 'Knock-Back', 0, '50, 100'), 
	(2, 'Fist', 'Strength', 'NA', 'NA', 'Small', 'Knock-Back', 0, '10, 70'), 
	(3, 'Ghastly Face', 'Strength', 'Large', 'Knock-Down', 'NA', 'Knock-Down', 20, '20, 40, 80'), 
	(1, 'Summon Doppleganger', 'Strength', 'NA', 'NA', 'Small', 'NA', 0, '50, 100'), 
	(3, 'Assassination', 'Strength', 'Medium', 'Flying', 'NA', 'Knock-Down', 20, '20, 40, 80'), 
	(1, 'Steel Storm', 'Strength', 'NA', 'NA', 'Small', 'Knock-Back', 0, '50, 100'), 
	(2, 'Shoot', 'Strength', 'NA', 'NA', 'Small', 'Knock-Back', 0, '10, 70'), 
	(3, 'Power Arrow', 'Strength', 'Large', 'Knock-Back', 'NA', 'NA', 20, '20, 40, 80'), 
	(1, 'Seismic Wave', 'Wisdom', 'NA', 'NA', 'Small', 'Knock-Down', 0, '50, 100'), 
	(3, 'Scorpion Sting', 'Wisdom', 'Large', 'Mid-Air', 'NA', 'NA', 20, '20, 40, 80'), 
	(1, 'Raging Arrow', 'Strength', 'NA', 'NA', 'Small', 'Knock-Down', 0, '50, 100'), 
	(3, 'Homing Arrow', 'Strength', 'Large', 'Knock-Back', 'NA', 'NA', 20, '20, 40, 80'), 
	(1, 'Crackling Twister', 'Strength', 'NA', 'NA', 'Small', 'Mid-Air', 0, '50, 100'), 
	(2, 'Stave Strike', 'Strength', 'NA', 'NA', 'Small', 'Knock-Down', 0, '10, 70'), 
	(3, 'Rick Rattle & Roll', 'Strength', 'Large', 'Knock-Down', 'NA', 'NA', 20, '20, 40, 80'), 
	(1, 'Aphrodites Favor', 'Wisdom', 'NA', 'NA', 'Small', 'Healing', 0, '50, 100'), 
	(2, 'Arcane Heard', 'Wisdom', 'NA', 'NA', 'Small', 'Knock-Back', 0, '10, 70'), 
	(3, 'Heart Power', 'Wisdom', 'Large', 'Knock-Back', 'NA', 'NA', 20, '20, 40, 80'), 
	(1, 'Spinning Hammer', 'Strength', 'NA', 'NA', 'Small', 'Knock-Back', 0, '50, 100'), 
	(3, 'Power Hammer', 'Strength', 'Large', 'Knock-Down', 'NA', 'NA', 20, '20, 40, 80'), 
	(1, 'Chain Slash', 'Strength', 'NA', 'NA', 'Small', 'Knock-Down', 0, '50, 100'), 
	(3, 'Charge', 'Strength', 'Large', 'Flying', 'NA', 'NA', 20, '20, 40, 80'), 
	(1, 'Spinning Spear', 'Strength', 'NA', 'NA', 'Small', 'Mid-Air', 0, '50, 100'), 
	(3, 'Piercing Spear', 'Strength', 'Large', 'Knock-Down', 'NA', 'NA', 20, '20, 40, 80'), 
	(1, 'Energy Pillar', 'Strength', 'NA', 'NA', 'Small', 'Mid-Air', 0, '50, 100'), 
	(3, 'Stunning Headbutt', 'Strength', 'Large', 'Knock-Back', 'NA', 'NA', 20, '20, 40, 80'), 
	(1, 'Laser Brain', 'Wisdom', 'NA', 'NA', 'Small', 'Knock-Back', 0, '50, 100'), 
	(2, 'Pistol', 'Wisdom', 'NA', 'NA', 'Small', 'Mid-Air', 0, '10, 70'), 
	(3, 'Violent Reaction', 'Wisdom', 'Large', 'Knock-Back', 'NA', 'NA', 20, '20, 40, 80'), 
	(1, 'Kamehameha', 'Strength', 'NA', 'NA', 'Large', 'Knock-Back', 0, '50, 100'), 
	(3, 'Shockwave', 'Strength', 'Large', 'Flying', 'NA', 'NA', 20, '20, 40, 80'), 
	(1, 'Balloon Blast', 'Wisdom', 'NA', 'NA', 'Small', 'Mid-Air', 0, '50, 100'), 
	(3, 'Massacre', 'Wisdom', 'Large', 'Knock-Down', 'NA', 'NA', 20, '20, 40, 80'), 
	(1, 'Ra 1', null, null, null, null, 'NA', 0, '50, 100'), 
	(2, 'Ra 2', null, null, null, null, null, 0, '10, 70'), 
	(3, 'Ra 3', null, null, 'Mid-Air', null, 'Mid-Air', 20, '20, 40, 80'), 
	(1, 'Set 1', null, null, null, null, 'Mid-Air', 0, '50, 100'), 
	(2, 'Set 2', null, null, null, null, null, 0, '10, 70'), 
	(3, 'Set 3', null, null, 'Knock-Down', null, 'Mid-Air', 20, '20, 40, 80'), 
	(1, 'Hellfire', 'Strength', 'NA', 'NA', 'Small', 'NA', 0, '50, 100'), 
	(2, 'Strike', 'Strength', 'NA', 'NA', 'Small', 'Knock-Down', 0, '10, 70'), 
	(3, 'Reapers Toil', 'Strength', 'Large', 'Knock-Down', 'NA', 'Mid-Air', 20, '20, 40, 80'), 
	(1, 'Ares 1', null, null, null, null, null, 0, '50, 100'), 
	(2, 'Ares 2', null, null, null, null, null, 0, '10, 70'), 
	(3, 'Ares 3', null, null, null, null, null, 20, '20, 40, 80'), 
	(1, 'Star Storm', 'Wisdom', 'NA', 'NA', 'Small', 'Knock-Down', 0, '50, 100'), 
	(2, 'Star Bomb', 'Wisdom', 'NA', 'NA', 'Small', 'Knock-Back', 0, '10, 70'), 
	(3, 'Star Blast', 'Wisdom', 'Large', 'Mid-Air', 'NA', 'Knock-Down', 20, '20, 40, 80'), 
	(1, 'Iron Werewolf 1', null, null, null, null, 'Mid-Air', 0, '50, 100'), 
	(2, 'Iron Werewolf 2', null, null, null, null, null, 0, '10, 70'), 
	(3, 'Iron Werewolf 3', null, null, 'Mid-Air', null, 'Knock-Back', 20, '20, 40, 80'), 
	(1, 'Bat Beast 1', null, null, null, null, 'Knock-Down', 0, '50, 100'), 
	(2, 'Bat Beast 2', null, null, null, null, null, 0, '10, 70'), 
	(3, 'Bat Beast 3', null, null, 'Knock-Back', null, 'Mid-Air', 20, '20, 40, 80');